/*
 *  This file is part of ManyNets.
 *
 *  ManyNets is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as 
 *  published by the Free Software Foundation, either version 3 of the 
 *  License, or (at your option) any later version.
 *
 *  ManyNets is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with ManyNets.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  ManyNets was created at the Human Computer Interaction Lab, 
 *  University of Maryland at College Park. See the README file for details
 */

package edu.umd.cs.hcil.manynets.ui;

import edu.umd.cs.hcil.manynets.engines.ExpressionCalculator;
import edu.umd.cs.hcil.manynets.engines.ExpressionCalculator.ColPrefix;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import prefuse.data.Table;

/**
 *
 * @author Manuel Freire
 */
public class PythonPanel extends javax.swing.JPanel {

    private static class ClassItem {
        private Class c;
        private ClassItem(Class c) { this.c = c; }
        @Override
        public String toString() { return c.getSimpleName(); }
    }

    /** Creates new form PythonPanel */
    public PythonPanel(Table table, String name) {
        initComponents();

        if (name == null) {
            jlTitle.setText("Python expression");
            jpNameAndType.setVisible(false);
            validate();
        } else {
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for (Class c : new Class[] { Integer.TYPE, Double.TYPE, Boolean.TYPE, String.class}) {
                m.addElement(new ClassItem(c));
            }
            jcbColType.setModel(m);
            jtfName.setText(name);
        }

        jtPython.setText("");

        String[] columnNames = new String[table.getColumnCount()];
        for (int i=0; i<columnNames.length; i++) {
            columnNames[i] = table.getColumnName(i);
        }
        jcbColumnSelect.setModel(new DefaultComboBoxModel(columnNames));
        jcbColumnOpSelect.setModel(new DefaultComboBoxModel(ColPrefix.values()));

        setPreferredSize(new Dimension(300,100));
    }

    public String getColName() {
        return jtfName.getText();
    }

    public Class getColType() {
        return ((ClassItem)jcbColType.getSelectedItem()).c;
    }

    public void setFilter(PythonPanel pp) {
        jtPython.setText(pp.jtPython.getText());
    }

    public void insertColumn(String colName) {
        jtPython.insert(
                ((ColPrefix)jcbColumnOpSelect.getSelectedItem()).prefix
                + ExpressionCalculator.getColExpression(colName),
                jtPython.getCaretPosition());
    }

    public String getText() {
        return jtPython.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPython = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jpNameAndType = new javax.swing.JPanel();
        jtfName = new javax.swing.JTextField();
        jlTitle1 = new javax.swing.JLabel();
        jcbColType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jcbColumnSelect = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jcbColumnOpSelect = new javax.swing.JComboBox();
        jbInsertRef = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jtPython.setColumns(20);
        jtPython.setRows(5);
        jScrollPane1.setViewportView(jtPython);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jScrollPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jlTitle.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlTitle.setText("Column name");
        jPanel1.add(jlTitle, new java.awt.GridBagConstraints());

        jPanel4.setLayout(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jpNameAndType.setLayout(new java.awt.GridBagLayout());

        jtfName.setColumns(16);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 11);
        jpNameAndType.add(jtfName, gridBagConstraints);

        jlTitle1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlTitle1.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jpNameAndType.add(jlTitle1, gridBagConstraints);

        jcbColType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpNameAndType.add(jcbColType, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jpNameAndType, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 4, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jcbColumnSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel2.add(jcbColumnSelect, gridBagConstraints);

        jPanel3.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints);

        jcbColumnOpSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanel2.add(jcbColumnOpSelect, gridBagConstraints);

        jbInsertRef.setText("Insert Reference");
        jbInsertRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertRefActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jbInsertRef, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 6, 0);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jbInsertRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertRefActionPerformed
        insertColumn("" + jcbColumnSelect.getSelectedItem());
    }//GEN-LAST:event_jbInsertRefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbInsertRef;
    private javax.swing.JComboBox jcbColType;
    private javax.swing.JComboBox jcbColumnOpSelect;
    private javax.swing.JComboBox jcbColumnSelect;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlTitle1;
    private javax.swing.JPanel jpNameAndType;
    private javax.swing.JTextArea jtPython;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables

}
